lib/tracker_web/router.ex
defmodule TrackerWeb.Router do
  use TrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    # After fetch_session in the browser pipeline:
    plug :get_current_user
    plug :fetch_flash
    #plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Below the pipeline
  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Tracker.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  scope "/", TrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/users/login", UserController, :login
    get "/tasks/assigned_tasks", TaskController, :assigned_tasks
    get "/landing", PageController, :landing
    post "/session",SessionController,:create
    delete "/session",SessionController,:delete

    resources "/users", UserController
    resources "/tasks", TaskController
    resources "/manages", ManageController

    resources "/time_blocks", Time_BlockController, except: [:new, :edit]
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", TrackerWeb do
    pipe_through :api
  end

end

lib/tracker_web/templates/page/index.html.eex
<div class="container">
  <div class="row">
    <h1 class="center-block">Welcome to Task Tracker!</h1>
  </div>
  <hr><br/>
  <div class="row">
    <h4>Users of your app should be able to:</h4>
    <ul>
      <li>Register an account</li>
      <li>Log in / Log out</li>
      <li>Assign tasks to themselves or other users</li>
      <li>Create Tasks, entering a title and a description</li>
      <li>Track how long they've worked on a task they're assigned to, in 15-minute increments.</li>
      <li>Mark a task as completed.</li>
    </ul>
  </div>
  <div class="row">
    <%= if !@current_user do %>
    <div class="col-md-6">
      <p>
        <a href=<%= user_path(@conn, :login) %> class="btn btn-primary">Login!</a>
      </p>
    </div>
    <div class="col-md-6">
      <a href=<%= user_path(@conn, :new) %> class="btn btn-info">Register!</a>
    </div>
    <% else %>
    <div class="col-md-6">
      <a href=<%= user_path(@conn, :new) %> class="btn btn-info">Register!</a>
    </div>
    <% end %>
  </div>
</div>

lib/tracker_web/templates/page/landing.html.eex
<%= if !@current_user do %>
<script>window.location.replace("<%=user_path(@conn, :login)%>");</script>
<% end %>
<div class="container">
  <div class="row">
    <h1 class="center-block">Task Tracker!</h1>
  </div>
  <hr><br/>
  <%= if @current_user.manager== "Yes" do %>
  <p>User Status: Manager!</p>
  <% else %>
  <p>User Status: Normal User</p>
  <% end %>
  <%= if @mName do %>
  <p>My Manager: <%= @mName %></p>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <p>
        <a href=<%= user_path(@conn, :index) %> class="btn btn-primary">List of Users</a>
      </p>
    </div>
    <div class="col-md-6">
      <p>
        <a href="/tasks/" class="btn btn-info">List of Assigned Tasks</a>
      </p>
    </div>
  </div>

  <%= if @current_user.manager== "Yes" do %>
  <div class="row">
    <div class="col-md-6">
      <p>
        <a href=<%= manage_path(@conn, :new) %> class="btn btn-info">Assign Subordinates</a>
      </p>
    </div>
    <div class="col-md-6">
      <p>
        <a href=<%= manage_path(@conn, :index) %> class="btn btn-primary">Manage Subordinates</a>
      </p>
    </div>
    <div class="col-md-6">
      <p>
        <a href=<%= task_path(@conn, :assigned_tasks) %> class="btn btn-success">List of Tasks Assigned to Subordinates</a>
      </p>
    </div>
  </div>
</div>
<%end%>